# CNNs {.unnumbered}

## Materials:
Date: TBD

### Pre-work:

1. Refresh ML foundations.
2. Read "The 100 page ML book" by Andiry Burkov. Chapters accessible [here](https://themlbook.com/wiki/doku.php)
3. [FFNs](./L01.qmd) 



### In-Class
1. CNNs Intro
    - [Chapter 7](https://d2l.ai/chapter_convolutional-neural-networks/index.html)[R05] covers topics like Invariance, Channels, Convolution Operation, Padding, Stride, Pooling.
    - [CNNs](https://www.cse.iitm.ac.in/~miteshk/CS7015/Slides/Handout/Lecture11.pdf)[R02]
2. Visualizations
    - [CNNs](https://www.cse.iitm.ac.in/~miteshk/CS7015/Slides/Handout/Lecture13.pdf)[R02]
3. CNN Architectures
    - [Chapter 8](https://d2l.ai/chapter_convolutional-modern/index.html)[R04] covers landmark CNN architectures such as AlexNet, VGG, ResNet, DenseNet.
    
### Lab
1. 1d CNNs (tbd)
2. 2d CNNs (tbd)

### Post-class:
1. \[notebook\] [ID Convolution](https://github.com/udlbook/udlbook/blob/main/Notebooks/Chap10/10_1_1D_Convolution.ipynb) R05
2. \[notebook\] [ID Convolution for MNSIT](https://github.com/udlbook/udlbook/blob/main/Notebooks/Chap10/10_2_Convolution_for_MNIST_1D.ipynb) R05
3. \[notebook\] [2D Convolution ](https://github.com/udlbook/udlbook/blob/main/Notebooks/Chap10/10_3_2D_Convolution.ipynb) R05
4. \[notebook\] [CNN for MNIST](https://github.com/udlbook/udlbook/blob/main/Notebooks/Chap10/10_5_Convolution_For_MNIST.ipynb) R05
5. \[youtube\] Lectures from R07
    - CNNs: An Intro [Part-1](https://www.youtube.com/watch?v=tH6uRl6f3bc&t), [part-2](https://www.youtube.com/watch?v=H_JtjeSNhA0)
    - Backprop in CNNS [youtube](https://www.youtube.com/watch?v=pUCCd2-17vI)
    - Evolution of CNNs for Image Classification [part-1](https://www.youtube.com/watch?v=rEFTKAXEBgY&t), [part-2](https://www.youtube.com/watch?v=YizB_RoGrMs)
    - Recent Architectures [youtube](https://www.youtube.com/watch?v=p047WxBf-qA&t) [as of 2021]
    - CNNs for Object Detection [Part-1](https://www.youtube.com/watch?v=yqyLWUKftI0), [Part-2](https://www.youtube.com/watch?v=VQXD6ZfYT6o) [Part-3](https://www.youtube.com/watch?v=JI-bxTnnSTg)
    - CNNs for Segmentation [youtube](https://www.youtube.com/watch?v=4zuAYazbCQ0)


### Papers
- [AlexNet](https://proceedings.neurips.cc/paper_files/paper/2012/file/c399862d3b9d6b76c8436e924a68c45b-Paper.pdf) - ImageNet Classification with Deep Convolutional Neural Networks
- [ZFNet](https://arxiv.org/abs/1311.2901v3) Visualizing and Understanding Convolutional Networks
- [VGGNet](https://arxiv.org/abs/1409.1556v6) Very Deep Convolutional Networks for Large-Scale Image Recognition
- [GooLeNet](https://arxiv.org/abs/1409.4842) Going Deeper with Convolutions
- [ResNet](https://arxiv.org/abs/1512.03385v1) Deep Residual Learning for Image Recognition
- [RCNN](https://arxiv.org/abs/1311.2524) Rich feature hierarchies for accurate object detection and semantic segmentation
-[Faster-RCNN](https://arxiv.org/abs/1506.01497) Faster R-CNN: Towards Real-Time Object Detection with Region Proposal Networks
- [YOLO](https://pjreddie.com/media/files/papers/yolo.pdf) You Only Look Once: Unified, Real-Time Object Detection
- [UNet](https://arxiv.org/abs/1505.04597) U-Net: Convolutional Networks for Biomedical Image Segmentation





